### ISSUE TITLE
Python 3.13 compatibility

### ISSUE THREAD

**Issue by dehnert** [mit-athena/python-afs#6]
Trying to build with Python 3.13 (and commit 300a92404859ed99a8d9db066b9526c363760e21, aka https://github.com/macathena/python-afs/tree/py3 -- which is dubiously appropriate for this repo, but Macathena doesn't have issues enabled)  gives:
```
* Getting build dependencies for wheel...
* Building wheel...
[1/1] Cythonizing afs/_util.pyx
/nix/store/wsrjvz1x8y73zcnsvf9wa3rl9vvj2532-python3.13-cython-3.0.12/lib/python3.13/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3)>
  tree = Parsing.p_module(s, pxd, full_module_name)
In file included from /nix/store/0m7q35xsmz8arjy18jfsshfqvf5ga7j8-openafs-1.8.13.2-dev/include/afs/prclient.h:11,
                 from afs/_util.c:1267:
/nix/store/0m7q35xsmz8arjy18jfsshfqvf5ga7j8-openafs-1.8.13.2-dev/include/ubik.h:171:17: error: field ‘cache_lock’ has incomplete type
  171 |     struct Lock cache_lock; /*!< protects cached application data */
      |                 ^~~~~~~~~~
error: command '/nix/store/rw8447qyjljmfiac0hhfc2jrspjnpn75-gcc-wrapper-14.2.1.20250322/bin/gcc' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```

It looks like Py3.13 ships with `include/python3.13/lock.h`, which conflicts with OpenAFS's `lock.h`.

I'm not actually sure what one usually does about this -- patch one of OpenAFS and Python as part of the build process?

**Comment by dehnert** [comment]
I guess the good news is this isn't a problem in any currently release LTS -- 25.04 introduced python3.13.

**Comment by geofft** [comment]
I wonder if you can convince Cython to put the OpenAFS headers first in the search path.

If it weren't Cython, you could try to build separate `.o` files, one using Python's CFLAGS and one using OpenAFS's.

But honestly I feel like this is a bug in both Python and OpenAFS. `<lock.h>` is too generic of a name. Python's is slightly better in that it's under the `python3.13` subdirectory; OpenAFS seems to install a `/usr/include/lock.h`!

**Comment by geofft** [comment]
I opened a CPython issue since these days I'm more familiar with that project, the breaking change was in CPython, and it seems like the header could be renamed without much trouble since it's recent and doesn't seem to be part of the documented API. It might also be worth trying to open an issue in OpenAFS, but given that the header name dates to at least OpenAFS 1.0 and presumably much longer in IBM/Transarc/CMU AFS, there might be backwards compatibility issues there.

**Comment by kaduk** [comment]
The OpenAFS lock.h seems to be an API from the legacy LWP threading model (though it is restricted to use with LWP-threaded code), which is largely deprecated in favor of the opr_lock.h routines.  So there would be some path to changing things in upstream OpenAFS, I think, though it would probably not be particularly fast.

**Comment by dehnert** [comment]
Looks like the Python change got merged into 3.13 and main (and a 3.14 PR exists, but that branch is broken currently) -- thanks Geoff.

Ben, would an OpenAFS PR be worth me submitting as well (`lock.h`->`lwp_lock.h`??)?

**Comment by dehnert** [comment]
Python update: per https://github.com/python/cpython/pull/137075#issuecomment-3126856020, the change is being reverted for 3.13 (too big for an already-stable release, which I can't say surprises me). [3.14's PR](https://github.com/python/cpython/pull/137072) hasn't been merged yet, and it sounds like it won't make it in either (though it hasn't yet been closed). From https://devguide.python.org/versions/ Python 3.15 will release in October 2026, so we'll need a solution for Ubuntu 26.04 LTS (uh, to the extent that Debathena still tries to have releases, anyway).

For OpenAFS, I went ahead and submitted https://gerrit.openafs.org/#/c/16496/1

**Comment by dehnert** [comment]
> I wonder if you can convince Cython to put the OpenAFS headers first in the search path.

Yes, but it's kinda messy.

The problem seems to be that Cython looks at the `include_dirs` and puts them with `-I whatever`, followed by the Python headers, again with `-I`. This *seems* like the right order, but since the OpenAFS include dir is `/usr/include` (at least here), gcc looks at that, says "ignoring duplicate directory "/usr/include" as it is a non-system directory that duplicates a system directory", and moves it later, so the upshot is that `/usr/include/python3.13` comes before the OpenAFS stuff.

This can be fixed by marking `/usr/include/python3.13` as a system dir with `-isystem`, which requires *also* re-marking `/usr/include` so it comes earlier. In `setup.py`, this seems to work:
```
@@ -19,7 +19,8 @@ for root in ['/Library/OpenAFS/Tools',
         break
 
 include_dirs = [os.path.join(os.path.dirname(__file__), 'afs'),
-                '%s/include' % root]
+                '%s/include' % root, ]
+system_include_dirs = ['%s/include' % root, '/usr/include/python3.13', ]
 library_dirs = ['%s/lib' % root,
                 '%s/lib/afs' % root]
 if os.path.exists('%s/lib/libafsauthent_pic.a' % root) or os.path.exists('%s/lib64/libafsauthent_pic.a' % root):
@@ -54,6 +55,7 @@ def PyAFSExtension(module, *args, **kwargs):
     kwargs.setdefault('library_dirs', []).extend(library_dirs)
     kwargs.setdefault('extra_link_args', []).extend(extra_link_args)
     kwargs.setdefault('define_macros', []).extend(define_macros)
+    kwargs.setdefault('extra_compile_args', []).extend([f'-isystem{dir}' for dir in system_include_dirs])
     return Extension(module,
                      ["%s.pyx" % module.replace('.', '/')],
                      *args,
```

I'm not really sure how we should feel about doing this. I guess at least we'd only need to do it for Py3.13/14.

(Also, I was originally trying this on NixOS, which introduces weird changes to the search path, so I switched to an Ubuntu docker container. Ubuntu doesn't switch librokenafs any more or something, so I used https://github.com/macathena/python-afs/tree/py3-debian. The test setup looks ilke:
```
docker run -it ubuntu:rolling /bin/bash
apt-get install python3-setuptools libopenafs-dev libkrb5-dev git cython3 heimdal-multidev
```

I haven't yet figured out how to fix this with Nix, which is a bit weirder since the actual paths that need to be marked system aren't fixed.)
